# .rubocop.yml

inherit_gem:
  rubocop-config: default.yml

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: False
  NewCops: enable

RSpec/DescribeClass:
  Exclude:
    - 'spec/multi_process_spec.rb'
